### PR TITLE
Allow displaying multiple roles (frontend-horse)

### PR DESCRIPTION
**Pull request by RedSparr0w**
Added multiple roles display for frontend-horse.

image

founder → mod → vip → subscriber

<details>
<summary>Generated from the following scss:</summary>

```scss
$mod-badge: '<path d="M7.05 13.406l3.534 3.536-1.413 1.414 1.415 1.415-1.414 1.414-2.475-2.475-2.829 2.829-1.414-1.414 2.829-2.83-2.475-2.474 1.414-1.414 1.414 1.413 1.413-1.414zM3 3l3.546.003 11.817 11.818 1.415-1.414 1.414 1.414-2.474 2.475 2.828 2.829-1.414 1.414-2.829-2.829-2.475 2.475-1.414-1.414 1.414-1.415L3.003 6.531 3 3zm14.457 0L21 3.003l.002 3.523-4.053 4.052-3.536-3.535L17.457 3z"></path>';
$vip-badge: '<path d="M3 3h18a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zm8 5.5v7h2v-7h-2zm-.285 0H8.601l-1.497 4.113L5.607 8.5H3.493l2.611 6.964h2L10.715 8.5zm5.285 5h1.5a2.5 2.5 0 1 0 0-5H14v7h2v-2zm0-2v-1h1.5a.5.5 0 1 1 0 1H16z"></path>';
$founder-badge: '<path style="transform: scale(0.045);" d="M509.8 332.5l-69.9-164.3c-14.9-41.2-50.4-71-93-79.2 18-10.6 46.3-35.9 34.2-82.3-1.3-5-7.1-7.9-12-6.1L166.9 76.3C35.9 123.4 0 238.9 0 398.8V480c0 17.7 14.3 32 32 32h236.2c23.8 0 39.3-25 28.6-46.3L256 384v-.7c-45.6-3.5-84.6-30.7-104.3-69.6-1.6-3.1-.9-6.9 1.6-9.3l12.1-12.1c3.9-3.9 10.6-2.7 12.9 2.4 14.8 33.7 48.2 57.4 87.4 57.4 17.2 0 33-5.1 46.8-13.2l46 63.9c6 8.4 15.7 13.3 26 13.3h50.3c8.5 0 16.6-3.4 22.6-9.4l45.3-39.8c8.9-9.1 11.7-22.6 7.1-34.4zM328 224c-13.3 0-24-10.7-24-24s10.7-24 24-24 24 10.7 24 24-10.7 24-24 24z"></path>';
$sub-badge: '<path d="M12 18.26l-7.053 3.948 1.575-7.928L.587 8.792l8.027-.952L12 .5l3.386 7.34 8.027.952-5.935 5.488 1.575 7.928z"></path>';

@mixin dualBadge($fill, $badge1, $badge2) {
  content: url('data:image/svg+xml; utf8, <svg fill="' + $fill + '" stroke="' + $fill + '" stroke-width="0" viewBox="0 0 54 24" height="1em" width="2.25em" xmlns="http://www.w3.org/2000/svg" style="display: inline;">' + $badge1 + '<g style="transform: translateX(30px)">' + $badge2 + '</g></svg>');
}

/* Multiple roles */
// vip +
[data-twitch-sender-roles~='vip'] {
    &[data-twitch-sender-roles~='subscriber'] .twitch-chat-sender::before {
        @include dualBadge('%23333333', $vip-badge, $sub-badge);
    }
}

// mod +
[data-twitch-sender-roles~='mod'] {
    &[data-twitch-sender-roles~='subscriber'] .twitch-chat-sender::before {
        @include dualBadge('white', $mod-badge, $sub-badge);
    }
    &[data-twitch-sender-roles~='vip'] .twitch-chat-sender::before {
        @include dualBadge('white', $mod-badge, $vip-badge);
    }
}

// founder +
[data-twitch-sender-roles~='founder'] {
    &[data-twitch-sender-roles~='subscriber'] .twitch-chat-sender::before {
        @include dualBadge('white', $founder-badge, $sub-badge);
    }
    &[data-twitch-sender-roles~='vip'] .twitch-chat-sender::before {
        @include dualBadge('white', $founder-badge, $vip-badge);
    }
    &[data-twitch-sender-roles~='mod'] .twitch-chat-sender::before {
        @include dualBadge('white', $founder-badge, $mod-badge);
    }
}

[data-twitch-sender-roles~=founder][data-twitch-sender-roles~=subscriber] .twitch-chat-sender::before,
[data-twitch-sender-roles~=founder][data-twitch-sender-roles~=vip] .twitch-chat-sender::before,
[data-twitch-sender-roles~=founder][data-twitch-sender-roles~=mod] .twitch-chat-sender::before,
[data-twitch-sender-roles~=mod][data-twitch-sender-roles~=subscriber] .twitch-chat-sender::before,
[data-twitch-sender-roles~=mod][data-twitch-sender-roles~=vip] .twitch-chat-sender::before,
[data-twitch-sender-roles~=vip][data-twitch-sender-roles~=subscriber] .twitch-chat-sender::before {
  margin-left: -2.55em;
}

[data-twitch-sender-roles~=founder][data-twitch-sender-roles~=subscriber] .twitch-chat-sender,
[data-twitch-sender-roles~=founder][data-twitch-sender-roles~=vip] .twitch-chat-sender,
[data-twitch-sender-roles~=founder][data-twitch-sender-roles~=mod] .twitch-chat-sender,
[data-twitch-sender-roles~=mod][data-twitch-sender-roles~=subscriber] .twitch-chat-sender,
[data-twitch-sender-roles~=mod][data-twitch-sender-roles~=vip] .twitch-chat-sender,
[data-twitch-sender-roles~=vip][data-twitch-sender-roles~=subscriber] .twitch-chat-sender {
  padding-left: 2.85em;
}
```
</details>

### CODE REVIEW

**Review by BenDMyers — CHANGES_REQUESTED** [review]
Howdy, @RedSparr0w! Thank you so much for contributing to this theme! It's taken me a little while to respond, because this theme was derived from the design of [Alex Trost's Frontend Horse streams'](https://twitch.tv/TrostCodes) chat overlays, and I wanted to check in with him that he was alright with the design changes before merging in other contributions.

I do notice that our CI's lint check is failing, namely because Stylelint is requesting some extra blank lines be added. Would you be willing to address the lint's requests before I merge it in?

Thank you!

**Comment by RedSparr0w** [comment]
> Howdy, @RedSparr0w! Thank you so much for contributing to this theme! It's taken me a little while to respond, because this theme was derived from the design of [Alex Trost's Frontend Horse streams'](https://twitch.tv/TrostCodes) chat overlays, and I wanted to check in with him that he was alright with the design changes before merging in other contributions.

No worries 👍 

> I do notice that our CI's lint check is failing, namely because Stylelint is requesting some extra blank lines be added. Would you be willing to address the lint's requests before I merge it in?

Linting should be fixed now

**Comment by NickyMeuleman** [comment]
Nice!
Wondering out loud, because I'm not sure it's possible using only CSS: Can the SVG paths be reused?
Right now each `<path>` in your SCSS code appears a single time, but in the CSS the same long strings are repeated.

It's not a huge deal as those are fairly tiny.

At first I thought "oh, I know, that's what the `<use>`-tag does" (Like in [this article by Sara Soueidan](https://tympanus.net/codrops/2015/07/16/styling-svg-use-content-css/)), but without access to the HTML, I'm not so sure how to accomplish this.

**Comment by RedSparr0w** [comment]
I don't believe they can be re-used with standard css.

AFAIK you can't concat text in css other than for `content:`
Otherwise it would have been doable with some css variables

**Comment by NickyMeuleman** [comment]
LGTM!
I'll check that CI message locally, as it doesn't provide any useful info here, but I think we're all good.

**Comment by BenDMyers** [comment]
@all-contributors Please add @RedSparr0w for design

**Review by BenDMyers — APPROVED** [review]

**Comment by NickyMeuleman** [comment]
It appears prettier got mad because of the linelength rule.
It would have been nice if the error said that somewhere.
All I did was save the file locally (thus running `prettier --write` on it).

Hope this does the co-authored thing now, I don't want to take @RedSparr0w's credit for this.
Ready to squah-merge.

**Pull request merged**
