### PR TITLE
Photos for OBS walkthrough

### PR DESCRIPTION
**Pull request by jennjunod**
These photos are to assist in #170

### CODE REVIEW

**Review by BenDMyers — CHANGES_REQUESTED** [review]
These screenshots look great, @jennjunod - thank you for taking the time to put them together!

Would you be willing to rename these image files to be a bit more descriptive? Even something like `src/assets/obs-docs-1.png` and so forth would be fine in my opinion.

**Comment by jennjunod** [comment]
Updated with obs-docs folder and renamed photos

**Review by BenDMyers — APPROVED** [review]
Awesome - thanks, Jenn!

**Comment by BenDMyers** [comment]
@all-contributors Please add @jennjunod for documentation

**Pull request merged**
